<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfouoec\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfouoec/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBfouoec.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBfouoec\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBfouoec\appProdProjectContainer([
    'container.build_hash' => 'Bfouoec',
    'container.build_id' => '223fc7e2',
    'container.build_time' => 1637325758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfouoec');
