<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEb4gx8t\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEb4gx8t/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEb4gx8t.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEb4gx8t\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEb4gx8t\appDevDebugProjectContainer([
    'container.build_hash' => 'Eb4gx8t',
    'container.build_id' => 'ff004854',
    'container.build_time' => 1637323917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEb4gx8t');
