<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4qnodpq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4qnodpq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4qnodpq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4qnodpq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4qnodpq\appDevDebugProjectContainer([
    'container.build_hash' => '4qnodpq',
    'container.build_id' => '201a0d49',
    'container.build_time' => 1637743831,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4qnodpq');
